### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by steveoh** [agrc/wmrc-skid#2]
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
    skidname[tests] 1.0.0 depends on arcgis==2.0.*
    ugrc-palletjack 2.2.0 depends on arcgis==1.9.*

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by jacobdadams** [comment]
Already fixed in dev branch.

**Comment by steveoh** [comment]
So do you need to rebase or something to get that to fix your function deployment? 

I checked the logs and `ModuleNotFoundError: No module named 'arcgis'` was the error.

**Comment by jacobdadams** [comment]
Yeah, I need to look into that more. I didn't have any of the environment secrets set up, so I'm fixing that first.
